services:
  trend-radar:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: trend-radar
    restart: unless-stopped

    volumes:
      - ../config:/app/config:ro
      - ../output:/app/output

    environment:
      - TZ=Asia/Shanghai
      - FEISHU_WEBHOOK_URL=${FEISHU_WEBHOOK_URL:https://www.feishu.cn/flow/api/trigger-webhook/92f746daf8c70dd15382239cf261ca7c}
      - CRON_SCHEDULE=${CRON_SCHEDULE:-*/5 * * * *}
      - RUN_MODE=${RUN_MODE:-cron}
      - IMMEDIATE_RUN=${IMMEDIATE_RUN:-true}
